# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-11 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicephone', models.CharField(default='', max_length=11, unique=True, verbose_name='终端手机号')),
                ('devicelongitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='终端GPS的经度')),
                ('devicelatitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='终端GPS的纬度')),
                ('deviceflag', models.SmallIntegerField(choices=[(0, 'normal'), (1, 'sos')], default=0, verbose_name='是否告警')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '终端信息',
                'verbose_name_plural': '终端信息',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='SosContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personname', models.CharField(default='', max_length=30, verbose_name='紧急联系人名字')),
                ('personphone', models.CharField(default='', max_length=11, unique=True, verbose_name='终端手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soscontactperson', to='DeviceManage.Device', verbose_name='绑定终端')),
            ],
            options={
                'verbose_name': '紧急联系人信息',
                'verbose_name_plural': '紧急联系人信息',
                'ordering': ('create_time',),
            },
        ),
    ]
