# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosGps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicelongitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='终端GPS的经度')),
                ('devicelatitude', models.CharField(blank=True, max_length=30, null=True, verbose_name='终端GPS的纬度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '终端gps坐标信息',
                'verbose_name_plural': '终端gps坐标信息',
                'ordering': ('update_time',),
            },
        ),
        migrations.AlterModelOptions(
            name='soscontactperson',
            options={'ordering': ('update_time',), 'verbose_name': '紧急联系人信息', 'verbose_name_plural': '紧急联系人信息'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='deviceflag',
        ),
        migrations.RemoveField(
            model_name='device',
            name='devicelatitude',
        ),
        migrations.RemoveField(
            model_name='device',
            name='devicelongitude',
        ),
        migrations.AddField(
            model_name='sosgps',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sosgps', to='DeviceManage.Device', verbose_name='绑定终端'),
        ),
    ]
