# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-12 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManage', '0002_auto_20190912_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soscontactperson',
            name='personphone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='紧急联系人手机号'),
        ),
    ]
