# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManage', '0004_device_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='终端ID'),
        ),
    ]
