# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManage', '0003_auto_20190912_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deviceid',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='终端ID'),
        ),
    ]
