# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-16 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DeviceManage', '0004_device_deviceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceid',
            new_name='devicemac',
        ),
    ]
